// Code generated by goctl. DO NOT EDIT.
package types

type HomeResp struct {
}

type UserRequest struct {
	Name     string `json:"name,optional"`
	Page     int    `json:"page,optional"`
	PageSize int    `json:"page_size,optional"`
}

type UserListResponse struct {
	List  []User `json:"users"`
	Total int64  `json:"total"`
}

type User struct {
	Id          int    `json:"id"`
	Identity    string `json:"identity"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	NowVolume   int    `json:"now_volume"`
	TotalVolume int    `json:"total_volume"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type SendEMailRequest struct {
	Email string `json:"email"`
}

type UserLoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type SendEMailUserResponse struct {
	Code int `json:"code"`
}

type UserResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserDetailResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
